### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/PythonNotebooks#4]
Volgende Python-modules laden niet in: keras, spacy en imp

**Comment by ngesquiere** [comment]
spacy is in orde
tensorflow staat wel op de server

Bij notebook Alexander 0500_StomataDetectie: keras is niet rechtstreeks te vinden, maar wel via  "from tensorflow import keras" maar enkel na upgrade van tensorflow

imp was probleem. Moest vervangen worden door importlib.util en heel wat code-aanpassingen. Ik denk dat dit redelijk gelukt is, maar omslachtig. 
Notebook Alexander werkt nog steeds niet. Ook problemen met de instructie MongoClient('mongodb://database:27017/') uit diep_neuraal_netwerk-kopie.py

[0500_StomataDetectie - Jupyter Notebook.pdf](https://github.com/dwengovzw/PythonNotebooks/files/7436544/0500_StomataDetectie.-.Jupyter.Notebook.pdf)

**Comment by tomneutens** [comment]
Ik herinner mij vaag dat Alexander inderdaad een databank gebruikte om data over voorgetrainde modelen uit te halen. Ik weet wel niet juist hoe dat werkte. Zullen we eens aan Francis moeten vragen, misschien heeft hij een dump van de databank?

**Comment by ngesquiere** [comment]
fixed zimcke image
